# Generated by Django 2.2.24 on 2023-03-17 13:35

from django.db import migrations
from edx_info_pages.models import PageType

PAGES = (
    'about',
    'contact',
    'faq',
    'help',
    'tos',
    'honor',
    'tos_and_honor',
    'privacy',
    'press',
    'blog',
    'donate',
)

def create_page_types(apps, schema_editor):
    for page_slug in PAGES:
        PageType.objects.get_or_create(slug=page_slug)


def delete_page_types(apps, schema_editor):
    PageType.objects.filter(slug__in=PAGES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('edx_info_pages', '0002_auto_20230317_1317'),
    ]

    operations = [
        migrations.RunPython(code=create_page_types, reverse_code=delete_page_types),
    ]
